name: tfsec
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - '**.tf'
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: tfsec
        id: tfsec
        run: |
          body="$(docker run --rm -t -v "$(pwd):/terraform" aquasec/tfsec --soft-fail --format json /terraform)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=result::$body"

      - run: echo "${{ steps.tfsec.outputs.result }}"

      - name: Comment pull request with tfsec result
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          repository: ${{ github.event.repository.full_name }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "${{ steps.tfsec.outputs.result }}"
