name: tfsec
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - '**.tf'
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: tfsec
        id: tfsec
        run: echo "::set-output name=result::$(docker run --rm -v "$(pwd):/terraform" aquasec/tfsec --soft-fail /terraform)"

      - name: Comment pull request with tfsec result
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          repository: ${{ github.event.repository.full_name }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.tfsec.outputs.result }}
