name: tfsec
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - '**.tf'
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true